env:
  browser: true
  es2021: true
extends:
  - google
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  "max-len": "off",
  "require-jsdoc": "off",
  "react/prop-types": "off"

}
